config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :entries

  root to: "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user

  default_scope { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    return redirect_to entries_path if user_signed_in?
    redirect_to new_session_path(User)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    entries = current_user.entries
    return redirect_to new_entry_path unless entries.any?
    render locals: { entries: current_user.entries }
  end

  def show
    entry = Entry.find(params[:id])
    render locals: { entry: entry }
  end

  def new
  end

  def create
    entry = Entry.new(entry_params)
    return redirect_to entry_path(entry) if entry.save!
    flash[:error] = "Something went wrong"
    redirect_to :back
  end

  def edit
    entry = Entry.find(params[:id])
    render locals: { entry: entry }
  end

  def update
    entry = Entry.find(params[:id])
    entry.update!(entry_params)
    flash[:success] = 'Diary entry updated!'
    redirect_to entry_path(entry)
  end

  def destroy
    entry = Entry.find(params[:id])
    entry.destroy!
    flash[:success] = 'Diary entry deleted!'
    redirect_to entries_path
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :body).merge(user_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/application/index.html.erb
<h1>hello</h1>

app/views/entries/_entry.html.erb
<article>
  <header>
    <h2><%= entry.title %></h2>
  </header>
  <main>
    <%= entry.body %>
  </main>
  <nav>
    <%= link_to 'Edit', edit_entry_path(entry) %>
    <%= link_to 'Delete', entry_path(entry), method: :delete %>
  </nav>
</article>

app/views/entries/_entry_form.html.erb
<% entry ||= Entry.new %>

<%= form_with model: entry do |form| %>

<%= form.text_field :title, placeholder: 'Enter your title here...' %>
<%= form.text_area :body, rows: 20 %>
<%= form.submit "Save Entry" %>

<% end %>

app/views/entries/edit.html.erb
<h1>Edit Entry</h1>
<%= render partial: 'entry_form', locals: { entry: entry } %>

app/views/entries/index.html.erb
<% entries.map do |entry| %>
  <%= render partial: 'entry', locals: { entry: entry } %>
<% end %>

app/views/entries/new.html.erb
<h1>New Entry</h1>
<%= render partial: 'entry_form' %>

app/views/entries/show.html.erb
<%= render partial: 'entry', locals: { entry: entry } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <header>
      <%= link_to 'Entries', entries_path %>
      <h1>Your Code Diary</h1>
      <%= link_to 'New Entry', new_entry_path %>
    </header>
    <% if flash[:notice].present? %>
      <p class="flash notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert].present? %>
      <p class="flash alert"><%= flash[:alert] %></p>
    <% end %>
    <% if flash[:success].present? %>
      <p class="flash success"><%= flash[:success] %></p>
    <% end %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>